### ISSUE TITLE
Problems working with HA 0.115 new broadlink integration

### ISSUE THREAD

**Issue by MYKSelf** [algirdasc/hass-floureon#4]
The component still works ok on this version, but the new homeassistant broadlink integration broke because the manifest blocks the py broadlink library to 0.14.0 and Home Assistant needs 0.14.1 at least to work.

I changed the requirement on the my manifest.json file, and it seems to work ok, both for the broadlink integration and hass-floureon component.

@algirdasc , can you please modify the library requirement to 0.14.1, if it's ok :) ?

```json
{
  "domain": "floureon",
  "name": "Floureon Thermostat",
  "documentation": "https://github.com/algirdasc/hass-floureon",
  "dependencies": [],
  "codeowners": ["@algirdasc"],
  "issue_tracker": "https://github.com/algirdasc/hass-floureon/issues",
  "requirements": ["pythoncrc", "broadlink==0.14.1"]
}
```

**Comment by algirdasc** [comment]
Thanks for your contribution. I've modified manifest, but unfortunately, I'm not able to test it right now.

**Comment by MYKSelf** [comment]
Seems to be working ok. Updated via HACS without problem, and both component and HA integration seems good. Thanks for the fast fix, @algirdasc  :)

**Comment by mesoulrock** [comment]
I have this same problem. I can't use new versions of Home Assistant because the integration of Broadlink devices is done natively, and it forces me to choose between integrating my thermostat (Beok BOT-313WiFi) with this custom_component or integrating my Broadlink devices (sp3 and RM mini 3) .
I have done the test: having the Broadlink devices correctly integrated, if I integrate this custom_component I lose them, however if I remove this integration I recover them.
Have you any solution occurs?
I don't know how I can show you the real problem, sorry, I'm a bit of a novice on this topic
